# Generated by Django 5.0.6 on 2024-06-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
